version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: csn_sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - csn_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  ai:
    build:
      context: ./src/ai-service
      dockerfile: Dockerfile
    container_name: csn_ai
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src/ai-service/model:/app/model:ro
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; print(requests.get('http://localhost:8000/health').status_code)"]
      interval: 15s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./src/Childsafenet.Api
      dockerfile: Dockerfile
    container_name: csn_api
    ports:
      - "7047:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=THANGNTB\\THANGNTB;Database=ChildSafeNet_DB;Trusted_Connection=True;TrustServerCertificate=True;;
      - AiService__BaseUrl=http://ai:8000
      - Jwt__Key=CHANGE_ME_SUPER_SECRET_KEY_1234567890
      - Jwt__Issuer=ChildSafeNet
      - Jwt__Audience=ChildSafeNet
    depends_on:
      sqlserver:
        condition: service_healthy
      ai:
        condition: service_healthy

  web:
    build:
      context: ./src/Childsafenet.Frontend
      dockerfile: Dockerfile
    container_name: csn_web
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE=http://localhost:7047
    depends_on:
      - api

volumes:
  csn_sql_data: